spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlDB:3306/xe
    username: root
    password: mysql
  
logging:
    level:
        web: debug
        com:
          bit:
            boot06: debug   