spring:
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://coocon.c3wlv6jbqwu8.ap-northeast-2.rds.amazonaws.com:5432/coocon
    username: postgres
    password: cooconcoocon
    hikari:
      maximum-pool-size:  5
      minimum-idle : 1
      idle-timeout: 60000
      connection-timeout : 60000
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver 
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: coocon
    
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.project.coocon.domain
    